version: '3'

services:  

  cig:
    image: andrewjouffray/composite_image_generator:latest
    restart: "no"

    # define all the imaeg generation settings
    environment:

      # define where to find the input data
      - input_path=raw_input_data/

      - dataset_name="salient_objects"

      - output_path=cig_test_output/

      - background_path=backgrounds/

      # define how to generate the images
      - max_objects_per_canvas=5

      - canvases_per_frame=2

      - canvas_lower_resolution=10

      - canvas_blurr=10

      - canvas_change_brightness=30

      - object_saturation=20

      - object_affine_transform=50

      # define how to save the output
      - save_box_yolo=true

      - save_box_PASCALVOC=true

      - save_masks_json=true

      - save_masks_yolo=true

      - save_masks_png=true
    
    # mount your folder like this: <path to your workfir>:/workdir
    volumes:
    - /run/media/andrew/research/workdir_salient_object:/workdir

    # don't touch this
    command: bash -c "cd /code/ && pwd && ls -l && ./start.sh"

